baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = 'Aviala Design'
theme = 'avialaStyle'

[menus]
  [[menus.main]]
    name = '主页'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = '博客'
    pageRef = '/blogs/'
    weight = 30

  [[menus.main]]
    name = '资源'
    pageRef = '/posts'
    weight = 20