baseURL = 'https://www.aviala.top/'
languageCode = 'zh-CN'
title = 'Aviala Design'
theme = 'avialaStyle'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = 'categories'
  tag = 'tags'

[menus]
  [[menus.main]]
    name = '主页'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = '博客'
    pageRef = '/blogs/'
    weight = 30

  [[menus.main]]
    name = '资源'
    pageRef = '/posts'
    weight = 20