import { defaultKnobValues, type KnobDef, type KnobValues } from "../components/DemoKnobs";
import {
  alertKnobs,
  alertLiveCode,
  anchorKnobs,
  anchorLiveCode,
  avatarKnobs,
  avatarLiveCode,
  badgeKnobs,
  badgeLiveCode,
  breadcrumbKnobs,
  breadcrumbLiveCode,
  buildAlertCode,
  buildAnchorCode,
  buildAvatarCode,
  buildBadgeCode,
  buildBreadcrumbCode,
  buildButtonCode,
  buildCardCode,
  buildCascaderCode,
  buildCheckboxCode,
  buildColorPickerCode,
  buildDatePickerCode,
  buildFeedbackCode,
  buildFormFieldCode,
  buildInputCode,
  buildLinkCode,
  buildListCode,
  buildLoadingCode,
  buildModalCode,
  buildNavigationCode,
  buildNumberInputCode,
  buildPageheadCode,
  buildPaginationCode,
  buildPopoverCode,
  buildProgressCode,
  buildRadioCode,
  buildScrollCode,
  buildScrollPickerCode,
  buildSegmentatorCode,
  buildSelectCode,
  buildSliderCode,
  buildStepsCode,
  buildSwitchCode,
  buildTabCode,
  buildTableCode,
  buildTagCode,
  buildTextareaCode,
  buildTimePickerCode,
  buildTooltipCode,
  buildTypefaceCode,
  buildTypographyCode,
  buildUploadCode,
  buttonKnobs,
  buttonLiveCode,
  cardKnobs,
  cardLiveCode,
  cascaderKnobs,
  cascaderLiveCode,
  checkboxKnobs,
  checkboxLiveCode,
  colorPickerKnobs,
  colorPickerLiveCode,
  datePickerKnobs,
  datePickerLiveCode,
  feedbackKnobs,
  feedbackLiveCode,
  formFieldKnobs,
  formFieldLiveCode,
  inputKnobs,
  inputLiveCode,
  linkKnobs,
  linkLiveCode,
  listKnobs,
  listLiveCode,
  loadingKnobs,
  loadingLiveCode,
  modalKnobs,
  modalLiveCode,
  navigationKnobs,
  navigationLiveCode,
  numberInputKnobs,
  numberInputLiveCode,
  pageheadKnobs,
  pageheadLiveCode,
  paginationKnobs,
  paginationLiveCode,
  popoverKnobs,
  popoverLiveCode,
  progressKnobs,
  progressLiveCode,
  radioKnobs,
  radioLiveCode,
  scrollKnobs,
  scrollLiveCode,
  scrollPickerKnobs,
  scrollPickerLiveCode,
  segmentatorKnobs,
  segmentatorLiveCode,
  selectKnobs,
  selectLiveCode,
  sliderKnobs,
  sliderLiveCode,
  stepsKnobs,
  stepsLiveCode,
  switchKnobs,
  switchLiveCode,
  tabKnobs,
  tabLiveCode,
  tableKnobs,
  tableLiveCode,
  tagKnobs,
  tagLiveCode,
  textareaKnobs,
  textareaLiveCode,
  timePickerKnobs,
  timePickerLiveCode,
  tooltipKnobs,
  tooltipLiveCode,
  typefaceKnobs,
  typefaceLiveCode,
  typographyKnobs,
  typographyLiveCode,
  uploadKnobs,
  uploadLiveCode,
} from "../demos/component-demos";

export type ComponentLiveApi = {
  knobs: KnobDef[];
  buildCode: (values: KnobValues) => string;
  liveCode: string;
};

/** DocPage `component` id → same knobs / buildCode as the 开发指南 live demo. */
const byComponent: Record<string, ComponentLiveApi> = {
  Alert: { knobs: alertKnobs, buildCode: buildAlertCode, liveCode: alertLiveCode },
  Anchor: { knobs: anchorKnobs, buildCode: buildAnchorCode, liveCode: anchorLiveCode },
  Avatar: { knobs: avatarKnobs, buildCode: buildAvatarCode, liveCode: avatarLiveCode },
  Badge: { knobs: badgeKnobs, buildCode: buildBadgeCode, liveCode: badgeLiveCode },
  Breadcrumb: {
    knobs: breadcrumbKnobs,
    buildCode: buildBreadcrumbCode,
    liveCode: breadcrumbLiveCode,
  },
  Button: { knobs: buttonKnobs, buildCode: buildButtonCode, liveCode: buttonLiveCode },
  Card: { knobs: cardKnobs, buildCode: buildCardCode, liveCode: cardLiveCode },
  CascaderField: { knobs: cascaderKnobs, buildCode: buildCascaderCode, liveCode: cascaderLiveCode },
  Checkbox: { knobs: checkboxKnobs, buildCode: buildCheckboxCode, liveCode: checkboxLiveCode },
  ColorPicker: {
    knobs: colorPickerKnobs,
    buildCode: buildColorPickerCode,
    liveCode: colorPickerLiveCode,
  },
  DatePickerField: {
    knobs: datePickerKnobs,
    buildCode: buildDatePickerCode,
    liveCode: datePickerLiveCode,
  },
  Feedback: { knobs: feedbackKnobs, buildCode: buildFeedbackCode, liveCode: feedbackLiveCode },
  FormField: { knobs: formFieldKnobs, buildCode: buildFormFieldCode, liveCode: formFieldLiveCode },
  Input: { knobs: inputKnobs, buildCode: buildInputCode, liveCode: inputLiveCode },
  Link: { knobs: linkKnobs, buildCode: buildLinkCode, liveCode: linkLiveCode },
  List: { knobs: listKnobs, buildCode: buildListCode, liveCode: listLiveCode },
  Loading: { knobs: loadingKnobs, buildCode: buildLoadingCode, liveCode: loadingLiveCode },
  Modal: { knobs: modalKnobs, buildCode: buildModalCode, liveCode: modalLiveCode },
  Navigation: {
    knobs: navigationKnobs,
    buildCode: buildNavigationCode,
    liveCode: navigationLiveCode,
  },
  NumberInput: {
    knobs: numberInputKnobs,
    buildCode: buildNumberInputCode,
    liveCode: numberInputLiveCode,
  },
  Pagehead: { knobs: pageheadKnobs, buildCode: buildPageheadCode, liveCode: pageheadLiveCode },
  Pagination: {
    knobs: paginationKnobs,
    buildCode: buildPaginationCode,
    liveCode: paginationLiveCode,
  },
  Popover: { knobs: popoverKnobs, buildCode: buildPopoverCode, liveCode: popoverLiveCode },
  Progress: { knobs: progressKnobs, buildCode: buildProgressCode, liveCode: progressLiveCode },
  RadioGroup: { knobs: radioKnobs, buildCode: buildRadioCode, liveCode: radioLiveCode },
  Scroll: { knobs: scrollKnobs, buildCode: buildScrollCode, liveCode: scrollLiveCode },
  ScrollPicker: {
    knobs: scrollPickerKnobs,
    buildCode: buildScrollPickerCode,
    liveCode: scrollPickerLiveCode,
  },
  SegmentatorGroup: {
    knobs: segmentatorKnobs,
    buildCode: buildSegmentatorCode,
    liveCode: segmentatorLiveCode,
  },
  Select: { knobs: selectKnobs, buildCode: buildSelectCode, liveCode: selectLiveCode },
  Slider: { knobs: sliderKnobs, buildCode: buildSliderCode, liveCode: sliderLiveCode },
  Steps: { knobs: stepsKnobs, buildCode: buildStepsCode, liveCode: stepsLiveCode },
  Switch: { knobs: switchKnobs, buildCode: buildSwitchCode, liveCode: switchLiveCode },
  Tab: { knobs: tabKnobs, buildCode: buildTabCode, liveCode: tabLiveCode },
  Table: { knobs: tableKnobs, buildCode: buildTableCode, liveCode: tableLiveCode },
  Tag: { knobs: tagKnobs, buildCode: buildTagCode, liveCode: tagLiveCode },
  Textarea: { knobs: textareaKnobs, buildCode: buildTextareaCode, liveCode: textareaLiveCode },
  TimePickerField: {
    knobs: timePickerKnobs,
    buildCode: buildTimePickerCode,
    liveCode: timePickerLiveCode,
  },
  Tooltip: { knobs: tooltipKnobs, buildCode: buildTooltipCode, liveCode: tooltipLiveCode },
  Typeface: { knobs: typefaceKnobs, buildCode: buildTypefaceCode, liveCode: typefaceLiveCode },
  Typography: {
    knobs: typographyKnobs,
    buildCode: buildTypographyCode,
    liveCode: typographyLiveCode,
  },
  Upload: { knobs: uploadKnobs, buildCode: buildUploadCode, liveCode: uploadLiveCode },
};

export function getComponentLiveApi(component: string): ComponentLiveApi | null {
  return byComponent[component] ?? null;
}

export function defaultLiveDemoCode(component: string): string | undefined {
  const api = getComponentLiveApi(component);
  if (!api) return undefined;
  const live = api.liveCode.trim();
  if (live) return live;
  return api.buildCode(defaultKnobValues(api.knobs));
}
