import { copyFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { findSpiralPackage, readSpiralVersion } from "./spiral-package.mjs";

// Component API tables are generated by react-docgen inside the Spiral monorepo.
// Releases after 0.0.2 ship the result as `@aviala-design/spiral/props.json`;
// the committed copy keeps the docs buildable against older published versions.
const dirname = path.dirname(fileURLToPath(import.meta.url));
const target = path.resolve(dirname, "../src/generated/props.json");

const packageDir = findSpiralPackage();
const source = packageDir ? path.join(packageDir, "dist/props.json") : null;

if (!source || !existsSync(source)) {
  if (!existsSync(target)) {
    console.error(
      "No props metadata available: install a Spiral release that ships props.json, or restore src/generated/props.json."
    );
    process.exit(1);
  }
  console.warn(
    `@aviala-design/spiral@${readSpiralVersion()} ships no props.json; using the committed src/generated/props.json.`
  );
  process.exit(0);
}

mkdirSync(path.dirname(target), { recursive: true });
copyFileSync(source, target);

const count = Object.keys(JSON.parse(readFileSync(target, "utf8"))).length;
console.log(`Synced ${count} component prop docs from @aviala-design/spiral@${readSpiralVersion()}`);
